### ISSUE TITLE
Helm Chart certmanager-issuer requirements/testing

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/mattermost-helm#117]
This suggestion was provided in this MR: https://gitlab.com/gitlab-org/charts/gitlab/merge_requests/767#63c75b578053b4cfeed7df755c9eafb8110770e8_0_31. 

"This will assume that you have installed a certmanager-issuer in the same namespace, but if this is a helm chart standalone from the gitlab helm chart, you probably havn't. So to make things work some additional steps are required.

(Optional but smooth) Setup some defaults for gitlabs certmanager.ingressShim
Install a ClusterIssuer
Add suitable annotation

1. (Optional) Setup default values for GitLab's certmanager Helm chart dependency
this is how i configured smooth defaults for my certmanager.
these are values provided to my gitlab helm chart
certmanager:
  ingressShim:
    defaultIssuerName: "letsencrypt-prod"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
2. Installed a cluster wide issuers manually (prod / staging)
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: redacted@example.com
    privateKeySecretRef:
      name: letsencrypt-prod-acme-key
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: redacted@example.com
    privateKeySecretRef:
      name: letsencrypt-staging-acme-key
    http01: {}
3. Configured your ingresses for various charts with certmanager compatible annotations
See: https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html#supported-annotations
(SEE: https://github.com/helm/charts/blob/master/stable/mattermost-team-edition/values.yaml#L39)
ingress:
  enabled: true
  annotations:
    ## If you have configured certmanager with default values, this will do
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: gitlab-nginx

    ## Without certmanager being configured with default values, you need to specify what issuer you want to use
    # kubernetes.io/ingress.class: gitlab-nginx
    # certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  hosts:
    - mattermost.example.com
  tls:
    - secretName: mattermost.example.com-tls
      hosts:
        - mattermost.example.com"

The current documentation is working as expected, but it would be helpful to have these steps tested against the process to ascertain whether they improve the process substantially and require documentation changes or if following them would have a negative impact on future versions. Any other feedback on the comments/proposed changes would be welcome.

**Comment by consideRatio** [comment]
> The current documentation is working as expected, but it would be helpful to have these steps tested against the process to ascertain whether they improve the process substantially and require documentation changes or if following them would have a negative impact on future versions. Any other feedback on the comments/proposed changes would be welcome.

There has been breaking changes to the cert-manager helm chart if i recall correctly, and these rely on the GitLab installation of cert-manager by GitLab. But I don't believe GitLab's helm chart has bumped to use these new versions yet. No I can verify that is the case, [they rely on cert-manager version 0.4.0](https://gitlab.com/gitlab-org/charts/gitlab/blob/master/requirements.yaml).

Note that the cert-manager helm chart has moved from https://github.com/helm/charts/tree/master/stable/cert-manager repo to https://github.com/jetstack/cert-manager, but if we rely on GitLab to install it, it only matters for GitLab.

**Comment by cpanato** [comment]
@consideRatio @justinegeffen the cert-manager breaking changes need to be addressed because if you try to use Letsencrypt it will not work anymore for older versions, need to use the release `release-0.12` 

but as you noted, if use the gitlab installation need to rely on that, or configure an extra one which is not the ideal thing to do

**Comment by cpanato** [comment]
will close due inactivity
