### ISSUE TITLE
 Crash Loop Back-off on OpenShift 3.11

### ISSUE THREAD

**Issue by xrow** [mattermost/mattermost-helm#122]
Hi,

after I install mattermost the mysql chart has a crash loop back off all the time.

The only and last message in the logs of the mysql container is 

"
Initializing database
"

**Comment by xrow** [comment]
https://github.com/helm/charts/issues/18688

I reportet this here

**Comment by xrow** [comment]
This can be fixed by using mysql 8.0.18

**Comment by OgulcanCankaya** [comment]
Dear @xrow,
Since it has been 1,5 years now, can this issue be closed ?

**Comment by xrow** [comment]
close
