### ISSUE TITLE
Unable to update to newest version: Problem with file storage settings

### ISSUE THREAD

**Issue by tech348712013870132** [mattermost/mattermost-helm#129]
After an update from v5.13.2 to v5.17.1 (mattermost-team-edition) (official helm chart kubernetes deployment) our mattermost instance throws the following error while starting:

`{"level":"error","ts":1575923795.6970422,"caller":"app/server_app_adapters.go:134","msg":"Problem with file storage settings: TestFileConnection: api.file.test_connection.local.connection.app_error, WriteFile: api.file.write_file_locally.writing.app_error, open data/testfile: permission denied"}`

The instance goes online nevertheless but all media files in all channels are missing now.
A rollback fixes this problem.

What do we have to additionally consider to be able to update our instance to the newest available version?

**Comment by belfhi** [comment]
Thanks for the heads up, I was wondering if I could just set the image tag to something more recent than `v5.13.2` but I think I will stick to the current version if it breaks things...

**Comment by cpanato** [comment]
closing this due inactivity

**Comment by tajpouria** [comment]
Giving root privileges to the default user using values .securityContext solved my issue.

```yaml
securityContext:
  fsGroup: 0
  runAsGroup: 0
  runAsUser: 0
```
