### ISSUE TITLE
[MM EE] Deprecated and removed apiVersions

### ISSUE THREAD

**Issue by g-linville** [mattermost/mattermost-helm#249]
As of right now, the Enterprise Edition chart only uses Ingress apiVersion `extensions/v1beta1` or `networking.k8s.io/v1beta1`:
https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-enterprise-edition/templates/_helpers.tpl#L49-#L55

Additionally, inside the mattermost-elasticsearch subchart, DaemonSet apiVersion `extensions/v1beta1` is being used, when that was removed back in Kubernetes 1.16:
https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-enterprise-edition/charts/mattermost-elasticsearch/templates/ds-master.yaml#L2

We are new users trying to install this on Kubernetes 1.19 and can't install this with elasticsearch enabled until the DaemonSet apiVersion is updated. The Ingress one is not a problem for now but will be for anyone wanting to use Kubernetes 1.22, when `networking.k8s.io/v1beta1` will be removed.

**Comment by jcstryker** [comment]
Any chance we can get the respective PR reviewed and merged? Right now this chart cannot be installed on a 1.22 cluster, as those beta API versions have been removed.
