### ISSUE TITLE
Incomplete license

### ISSUE THREAD

**Issue by pandatix** [mattermost/mattermost-helm#264]
Hi, travelling through this repo, I saw that you did not fill all the license (https://github.com/mattermost/mattermost-helm/blob/master/LICENSE.txt#L189).

Technically, while it's not filled, we can't exactly know if this repository is really promoted with an Apache License-2.0 or is proprietary.

**Comment by jasonblais** [comment]
@pandatix Thanks for raising this.

The Apache 2.0 license includes an Appendix, which has the reference to `copyright {yyyy} {name of copyright owner}`.

This reference is intended for others who can apply the Apache license to their work, and is meant as a template to be replaced when using this project. Thus, from my understanding it should not be modified in this case.

You can see a related discussion at https://github.com/kubernetes/kubernetes/pull/37305
