### ISSUE TITLE
Missing Team Edition Helm Chart for latest version (6.0.1)

### ISSUE THREAD

**Issue by lfvjimisola** [mattermost/mattermost-helm#269]
Not an issue per se but unable to figure out what the lead time is between a Mattermost release and a matching release of the Team Edition Helm Chart. Is there a timeline? Ideally the Helm Charts would be available at the same time as the Mattermost release.

**Comment by lfvjimisola** [comment]
@cpanato There are a few other issues regarding upgrades that seem to hint that the PVC in to reused and that data is used.
Is it safe to upgrade (without data loss) with the helm chart?

**Comment by cpanato** [comment]
@lfvjimisola I did some tests and one was an upgrade test from 5.39 to 6.0 and before that, I made some posts, upload images... and after the upgrade, everything was there.

i would say, before you run the upgrade run a dry run and check the manifests and see if those are ok

**Comment by lfvjimisola** [comment]
@cpanato Great. Thanks. However, latest version is 6.0.1 and it has some important bug fixes apparently.

**Comment by lfvjimisola** [comment]
Our upgrade worked flawlessly. Thanks.
