### ISSUE TITLE
[MATTERMOST] helm charts - ApiVersion

### ISSUE THREAD

**Issue by HujinoKun** [mattermost/mattermost-helm#280]
Hello,

Following a version upgrade on kubernetes to 1.22.

The _helper file is no longer good on the api version of the networking module.

Error : 

```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

Since 1.19, the networking.k8s.io/v1 api is available and it is native on version 1.22.

Could you add this to the _helper file: 

```
{{- if semverCompare "^1.19-0" .Capabilities.KubeVersion.GitVersion -}}
"networking.k8s.io/v1"
```

**Comment by acuteaura** [comment]
That wouldn't be sufficient, since v1 also adds some extra changes:

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by EugenMayer** [comment]
@acuteaura is right, the current resource is not usable right now without fixing the actual structure / deprecations

**Comment by theAkito** [comment]
Is there at least an easy workaround available?

**Comment by HujinoKun** [comment]
Please, upgrade the helm charts with latest version of ingress
