### ISSUE TITLE
Add various custom config.json options missing in helm's configJson

### ISSUE THREAD

**Issue by lfvjimisola** [mattermost/mattermost-helm#291]
It seems as if various custom config.json options are missing in the helm chart (ref values.yml.

For example:

TeammateNameDisplay
ReplyToAddress
EnableEmailInvitations

**Comment by pat-s** [comment]
`configJSON` has been completely removed AFAICS, so this issue can be closed.

**Comment by lfvjimisola** [comment]
@pat-s We missed that. Thanks.
