### ISSUE TITLE
9.0 update?

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-helm#420]
When is the chart going to be updated to support Mattermost 9.0?

**Comment by mrvnklm** [comment]
my version is even still stuck to mattermost v7.10.0, do I have to update manually instead updating the release?

**Comment by bbodenmiller** [comment]
Looks like it was updated now

**Comment by mrvnklm** [comment]
For me the server version is still 7 even though updating to the latest helm chart, any ideas?
