### ISSUE TITLE
[mattermost-team-edition] Allow extra pod annotations

### ISSUE THREAD

**Issue by sebastien-prudhomme** [mattermost/mattermost-helm#79]
Hi,

My use case is to backup Mattermost with Velero/Restic application. This works if the pod has an annotation like this one:

```
backup.velero.io/backup-volumes: "mattermost-data"
```

The chart doesn't yet allow to add such annotation.

I propose to add a new parameter in values.yaml:

```
## Additional pod annotations
extraPodAnnotations: {}
```

**Comment by cpanato** [comment]
@sebastien-prudhomme thanks for the report, are you willing to open a PR to fix this?

**Comment by sebastien-prudhomme** [comment]
@cpanato ok
