### ISSUE TITLE
Multiple replicas

### ISSUE THREAD

**Issue by Stolr** [mattermost/mattermost-helm#87]
Some folders are not defined in volumes ( plugins for example ).

The chart does not work with multiple replicas.

**Comment by amyblais** [comment]
Hi @Stolr, would you be open to sharing more details on your issue, including repro steps, observed and expected? Also, would you be open to creating a pull request for this?

**Comment by Stolr** [comment]
Hi ,

Sorry , I am using team edition and haven't seen before that having multiple replicas is not possible with this edition.

I'm closing the issue


Regards

**Comment by cpanato** [comment]
MM-TE does not support multiple pods

closing this issue
