### ISSUE TITLE
how can we use plugins?

### ISSUE THREAD

**Issue by ahmadalli** [mattermost/mattermost-helm#91]
since system console settings are read-only, would you please provide an example for enabling plugins (e.g. jira)?

**Comment by ahmadalli** [comment]
https://github.com/helm/charts/issues/12957

**Comment by amyblais** [comment]
Hi @ahmadalli,

Wondering if this post might help: https://forum.mattermost.org/t/documentation-for-installing-plugins-when-using-helm/7384?

**Comment by ahmadalli** [comment]
@amyblais my question is what's the format of `Plugins: {}` and `PluginState: {}`. I couldn't find that on the url you provided

**Comment by zakkg3** [comment]
It seems the PVC its for `/mattermost/data` and the plugins are in /mattermost (the working dir) / plugins
so if the pod is restarted  the plugins are lost...  I configured the plugins directory inside the data one (inside the pvc) but i get 501 error....
its not clear how plugins should be used. :/

**Comment by agusl88** [comment]
@zakkg3 https://github.com/mattermost/mattermost-helm/pull/108

**Comment by belfhi** [comment]
I'm figuring this out myself right now. 
What I have managed is to activate plugins that I uploaded in the UI by setting the pluginstate to the following value (for the matterpoll plugin in this case):
```
PluginState: {
      "com.github.matterpoll.matterpoll": {
        "Enable": true
        },
   }
```
I'm still trying to understand how to do the `Plugins: {}` part but I think one needs to use the keys that are defined in the `plugin.json` file

**Comment by cpanato** [comment]
for MM-TE with this PR https://github.com/mattermost/mattermost-helm/pull/225 the configuration will be in the DB and you will be able to change the config in the system console

will close this
